### ISSUE TITLE
Postgres cache issue

### ISSUE THREAD

**Issue by luffybhaagi** [redstone-finance/redstone-smartcontracts#80]
``` ts
import knex from "knex";
import { LoggerFactory, SmartWeaveNodeFactory } from "redstone-smartweave";
import Client from "../utils/init";
import fs from 'fs'

const knexConfig = knex({
    client: 'pg',
    connection: 'postgres://redstone:redstone@localhost:5432/smartweave',
    searchPath: ['knex', 'public'],
    useNullAsDefault: true
})

const wallet = JSON.parse(fs.readFileSync("./wallet.json") as unknown as string);

async function KnexCached() {
    const smartweave = await SmartWeaveNodeFactory.knexCached(Client, knexConfig)
    LoggerFactory.INST.logLevel("debug", "Read contract interactions")

    const contractTxId = "-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ"
    const contract = smartweave.contract(contractTxId).connect(wallet)
    const { state, validity } = await contract.readState()
    
    console.log(state);
    console.log(validity);
}

KnexCached().catch(e => console.log(e))
```

I'm trying to read contract state using knex, postgres. I'm getting below error Can you please tell anything wrong in code or setup? 

```code
warning ../package.json: No license field
$ ts-node -r dotenv/config ./scripts/redstone/read.knex.cache.ts
error: select "contract_id", "height", "state", max("height") from "states" group by "contract_id" order by "height" desc - column "states.height" must appear in the GROUP BY clause or be used in an aggregate function
    at Parser.parseErrorMessage (ar-contracts/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (ar-contracts/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (ar-contracts/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (ar-contracts/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 176,
  severity: 'ERROR',
  code: '42803',
  detail: undefined,
  hint: undefined,
  position: '23',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_agg.c',
  line: '1419',
  routine: 'check_ungrouped_columns_walker'
}
```

**Comment by ppedziwiatr** [comment]
duplicates https://github.com/redstone-finance/redstone-smartcontracts/issues/78
